// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHCXY59Mn2JZER6QnpjrNeKF-WC3g3JQ',
    appId: '1:428396765973:web:447eb626a5d80d5d1eff1c',
    messagingSenderId: '428396765973',
    projectId: 'project-sora-4e04e',
    authDomain: 'project-sora-4e04e.firebaseapp.com',
    storageBucket: 'project-sora-4e04e.firebasestorage.app',
    measurementId: 'G-YW4CTP49RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwdWmuB01yKN5ZwLDLRDr2iZNUakwyVRQ',
    appId: '1:428396765973:android:5043816c41b70ba01eff1c',
    messagingSenderId: '428396765973',
    projectId: 'project-sora-4e04e',
    storageBucket: 'project-sora-4e04e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHmxdGaOwIcgQb1BJSiqdZtHn0blvIBmc',
    appId: '1:428396765973:ios:36f5a3cd962286771eff1c',
    messagingSenderId: '428396765973',
    projectId: 'project-sora-4e04e',
    storageBucket: 'project-sora-4e04e.firebasestorage.app',
    iosBundleId: 'com.example.solarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHmxdGaOwIcgQb1BJSiqdZtHn0blvIBmc',
    appId: '1:428396765973:ios:36f5a3cd962286771eff1c',
    messagingSenderId: '428396765973',
    projectId: 'project-sora-4e04e',
    storageBucket: 'project-sora-4e04e.firebasestorage.app',
    iosBundleId: 'com.example.solarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHHCXY59Mn2JZER6QnpjrNeKF-WC3g3JQ',
    appId: '1:428396765973:web:f8ec67427417aa0e1eff1c',
    messagingSenderId: '428396765973',
    projectId: 'project-sora-4e04e',
    authDomain: 'project-sora-4e04e.firebaseapp.com',
    storageBucket: 'project-sora-4e04e.firebasestorage.app',
    measurementId: 'G-T2VM8BRDKW',
  );
}
