// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2K7qVQjK4SAzMVE7FbTrvAXJ7yDgl1JM',
    appId: '1:110774688188:web:e43dff6ab1a486708233b9',
    messagingSenderId: '110774688188',
    projectId: 'sora-project-f7bad',
    authDomain: 'sora-project-f7bad.firebaseapp.com',
    storageBucket: 'sora-project-f7bad.firebasestorage.app',
    measurementId: 'G-V8J12S7SHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9FO1dorb1tSol_d1OOb-oZKTuiGsWq2Q',
    appId: '1:110774688188:android:02c42b7bc4bb2d768233b9',
    messagingSenderId: '110774688188',
    projectId: 'sora-project-f7bad',
    storageBucket: 'sora-project-f7bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB11xuns12mEeyUWxlKpSc2yK75BPdKuis',
    appId: '1:110774688188:ios:395f8da4afe64fbc8233b9',
    messagingSenderId: '110774688188',
    projectId: 'sora-project-f7bad',
    storageBucket: 'sora-project-f7bad.firebasestorage.app',
    iosBundleId: 'com.example.solarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB11xuns12mEeyUWxlKpSc2yK75BPdKuis',
    appId: '1:110774688188:ios:395f8da4afe64fbc8233b9',
    messagingSenderId: '110774688188',
    projectId: 'sora-project-f7bad',
    storageBucket: 'sora-project-f7bad.firebasestorage.app',
    iosBundleId: 'com.example.solarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2K7qVQjK4SAzMVE7FbTrvAXJ7yDgl1JM',
    appId: '1:110774688188:web:193b84ed83e8a6988233b9',
    messagingSenderId: '110774688188',
    projectId: 'sora-project-f7bad',
    authDomain: 'sora-project-f7bad.firebaseapp.com',
    storageBucket: 'sora-project-f7bad.firebasestorage.app',
    measurementId: 'G-59ZJPT7B93',
  );
}
